///////////////////////////////////////////////////////////
//  Styler.cs
//  Implementation of the Class Styler
//  Generated by Enterprise Architect
//  Created on:      13-2ÔÂ-2017 0:22:35
//  Original author: Doku
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace VWG.Community.Forms.Model.ECharts.gmap
{
    public class Styler
    {
        #region Properties
        public string color { get; set; }

        public VisibilityType? visibility { get; set; }
        #endregion

        #region Methods
        /// 
        /// <param name="color"></param>
        public Styler Color(string color)
        {
            this.color = color;
            return this;
        }

        /// 
        /// <param name="visibility"></param>
        public Styler Visibility(VisibilityType visibility)
        {
            this.visibility = visibility;
            return this;
        }
        #endregion
    }//end Styler

}//end namespace bmap