///////////////////////////////////////////////////////////
//  VisibilityType.cs
//  Implementation of the Enumeration VisibilityType
//  Generated by Enterprise Architect
//  Created on:      13-2ÔÂ-2017 0:22:35
//  Original author: Doku
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace VWG.Community.Forms.Model.ECharts.gmap {
	public enum VisibilityType  {

		/// <summary>
		/// ÏÔÊ¾
		/// </summary>
		on,
		/// <summary>
		/// Òþ²Ø
		/// </summary>
		off

	}//end VisibilityType

}//end namespace bmap