///////////////////////////////////////////////////////////
//  EffectScatter.cs
//  Implementation of the Class EffectScatter
//  Generated by Enterprise Architect
//  Created on:      15-2ÔÂ-2017 22:04:53
//  Original author: Doku
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

using VWG.Community.Forms.Model.ECharts.series;

namespace VWG.Community.Forms.Model.ECharts.series
{
    public class EffectScatter : Scatter
    {
        #region Properties
        public string effectType { get; set; }

        public ShowEffectType showEffectOn { get; set; }

        public RippleEffect rippleEffect { get; set; }
        #endregion

        #region Methods
        public EffectScatter EffectType(string effectType)
        {
            this.effectType = effectType;
            return this;
        }

        public EffectScatter ShowEffectOn(ShowEffectType showEffectOn)
        {
            this.showEffectOn = showEffectOn;

            return this;
        }

        public RippleEffect RippleEffect()
        {
            if (this.rippleEffect == null)
                rippleEffect = new RippleEffect();
            return rippleEffect;
        }

        public RippleEffect RippleEffect(RippleEffect rippleEffect)
        {
            this.rippleEffect = rippleEffect;
            return rippleEffect;
        }

        public EffectScatter()
        {
            this.type = ChartType.effectScatter;
        }

        public EffectScatter(string name)
            : this()
        {
            this.name = name;
        }
        #endregion
    }//end EffectScatter

}//end namespace series